name: Deploy to Cloud Run
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # DEPLOY BACKEND (Configurado com Banco e CORS)
      - name: Deploy Backend
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'milagres-backend'
          region: 'us-central1'
          source: './backend'
          env_vars: |
            MONGO_URL=${{ secrets.MONGO_URI }}
            DB_NAME=milagres-db
            CORS_ORIGINS=*
            JWT_SECRET=segredo-seguro-viasacra
          flags: '--allow-unauthenticated --max-instances=1 --memory=512Mi'

      # DEPLOY FRONTEND
      - name: Deploy Frontend
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'milagres-frontend'
          region: 'us-central1'
          source: './frontend'
          flags: '--allow-unauthenticated --max-instances=1 --memory=512Mi'
