name: Deploy to Cloud Run
on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: solar-simulator-486100
  GAR_LOCATION: us-central1
  REPOSITORY: milagres-repo

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # DEPLOY BACKEND (Configurado com Banco e CORS)
      - name: Deploy Backend
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'milagres-backend'
          region: 'us-central1'
          source: './backend'
          env_vars: |
            MONGO_URL=${{ secrets.MONGO_URI }}
            DB_NAME=milagres-db
            CORS_ORIGINS=*
            JWT_SECRET=segredo-seguro-viasacra
          flags: '--allow-unauthenticated --max-instances=1 --memory=512Mi'

      - name: Build and Push Container (Frontend)
        run: |-
          docker build \
            --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/milagres-frontend:${{ github.sha }}" \
            ./frontend
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/milagres-frontend:${{ github.sha }}"
